[package]
name = "sabun"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
similar = "2.0"
termcolor = "1.1"
crossterm = "0.27"
atty = "0.2"
anyhow = "1.0"
